Traceback (most recent call last):
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/pavanchaggar/Documents/NetworkInference/env/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class MyNetworkFKPPModel(Model):

    def f(self, p, t, theta):
        k, a = theta
        du = k * (-self.L() @ p) + (a * p) * (1 - p)
        return du

    def solve(self, p, theta):
        return odeint(self.f, p, self.t, args=(theta,))

    def forward(self, u0):
        p = np.exp(u0[:-2])
        theta = np.exp(u0[-2:])

        u = self.solve(p, theta)
        return u

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-312f4b92ae46>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mclass[0m [0mMyNetworkFKPPModel[0m[0;34m([0m[0mModel[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m     [0;32mdef[0m [0mf[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mp[0m[0;34m,[0m [0mt[0m[0;34m,[0m [0mtheta[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m         [0mk[0m[0;34m,[0m [0ma[0m [0;34m=[0m [0mtheta[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m         [0mdu[0m [0;34m=[0m [0mk[0m [0;34m*[0m [0;34m([0m[0;34m-[0m[0mself[0m[0;34m.[0m[0mL[0m[0;34m([0m[0;34m)[0m [0;34m@[0m [0mp[0m[0;34m)[0m [0;34m+[0m [0;34m([0m[0ma[0m [0;34m*[0m [0mp[0m[0;34m)[0m [0;34m*[0m [0;34m([0m[0;36m1[0m [0;34m-[0m [0mp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Model' is not defined
NameError: name 'Model' is not defined

